export default {
  SET_WALLET: 'SET_WALLET',
  SET_BALANCE: 'SET_BALANCE',
  GET_BALANCE: 'GET_BALANCE',
  SEND: 'SEND',
  ADD_HISTORY: 'ADD_HISTORY',
  CHANGE_PATH: 'CHANGE_PATH',
  CHANGE_ADDRESS: 'CHANGE_ADDRESS',
  QUIT: 'QUIT',
};
